/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories/index'
import { Route as MemoriesMemoryIdRouteImport } from './routes/memories/$memoryId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesMemoryIdRoute = MemoriesMemoryIdRouteImport.update({
  id: '/memories/$memoryId',
  path: '/memories/$memoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/memories/$memoryId' | '/memories/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/memories/$memoryId' | '/memories'
  id: '__root__' | '/' | '/search' | '/memories/$memoryId' | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  MemoriesMemoryIdRoute: typeof MemoriesMemoryIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$memoryId': {
      id: '/memories/$memoryId'
      path: '/memories/$memoryId'
      fullPath: '/memories/$memoryId'
      preLoaderRoute: typeof MemoriesMemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  MemoriesMemoryIdRoute: MemoriesMemoryIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
